apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: gromacs
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: gromacs
spec:
  output:
    to:
      kind: ImageStreamTag
      name: gromacs:latest
  source:
    dockerfile: |-
      # Build stage with Spack pre-installed and ready to be used
      FROM spack/fedora38:v0.20.1 as builder

      # What we want to install and how we want to install it
      # is specified in a manifest file (spack.yaml)
      RUN mkdir /opt/spack-environment \
      &&  (echo spack: \
      &&   echo '  specs:' \
      &&   echo '  - gromacs+mpi' \
      &&   echo '  - mpich' \
      &&   echo '' \
      &&   echo '  concretizer:' \
      &&   echo '    unify: true' \
      &&   echo '  config:' \
      &&   echo '    install_tree: /opt/software' \
      &&   echo '  view: /opt/view') > /opt/spack-environment/spack.yaml

      # Install the software, remove unnecessary deps
      RUN . /opt/spack/share/spack/setup-env.sh && \
          cd /opt/spack-environment && \
          spack env activate . && \
          spack install --fail-fast && \
          spack gc -y

      # Strip all the binaries
      RUN find -L /opt/view/* -type f -exec readlink -f '{}' \; | \
          xargs file -i | \
          grep 'charset=binary' | \
          grep 'x-executable\|x-archive\|x-sharedlib' | \
          awk -F: '{print $1}' | xargs strip

      # Modifications to the environment that are necessary to run
      RUN . /opt/spack/share/spack/setup-env.sh && \
          cd /opt/spack-environment && \
          spack env activate --sh -d . > activate.sh


      # Bare OS image to run the installed executables
      FROM docker.io/fedora:38

      COPY --from=builder /opt/spack-environment /opt/spack-environment
      COPY --from=builder /opt/software /opt/software
      COPY --from=builder /opt/._view /opt/._view
      COPY --from=builder /opt/view /opt/view

      RUN { \
            echo '#!/bin/sh' \
            && echo '.' /opt/spack-environment/activate.sh \
            && echo 'exec "$@"'; \
          } > /entrypoint.sh \
      &&  chmod a+x /entrypoint.sh


      ENTRYPOINT [ "/entrypoint.sh" ]
      CMD [ "/bin/bash" ]

  strategy:
    dockerStrategy: {}
