apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: gromacs-data
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: gromacs-data
spec:
  output:
    to:
      kind: ImageStreamTag
      name: gromacs-data:latest
  source:
    dockerfile: |-
      FROM image-registry.openshift-image-registry.svc:5000/mpi-testing/gromacs:latest

      RUN dnf install -y unzip openssh-server openssh-clients && \
          curl -Lo benchMEM.zip https://www.mpinat.mpg.de/benchMEM && \
          unzip benchMEM.zip

  strategy:
    dockerStrategy: {}
