namespace: slurm-system

commonLabels:
  app: slurm

resources:
  - namespace.yaml
  - service.yaml
  - statefulset-head.yaml
  - statefulset-compute.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - claim.yaml
  - priorityclass.yaml

  - servicemonitor.yaml
  - scaledobject.yaml
  - serviceaccount-slurm-metrics.yaml

configMapGenerator:
- name: slurm-conf
  files:
    - configs/slurm.conf
  options:
    disableNameSuffixHash: true
    labels:
      app: slurm
- name: cgroup-conf
  files:
    - configs/cgroup.conf
