apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  # annotations:
  #   autoscaling.keda.sh/paused-replicas: "0" 
  name: scaledobject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: compute
  cooldownPeriod:  60
  maxReplicaCount: 10
  minReplicaCount: 0
  fallback: 
    failureThreshold: 3
    replicas: 1
  pollingInterval: 30
  # advanced:
  #   scalingModifiers:
  #     activationTarget: "2"
  #   horizontalPodAutoscalerConfig:
  #     behavior:
  #       scaleDown:
  #         stabilizationWindowSeconds: 150
  #         policies:
  #           - type: Percent
  #             value: 100
  #             periodSeconds: 15
  triggers:
  - type: prometheus 
    metadata:
      serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
      namespace: slurm-system
      query: slurm_queue_pending
      threshold: '1'
      authModes: bearer
    authenticationRef:
      name: prom-triggerauthentication
      kind: TriggerAuthentication
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: prom-triggerauthentication
spec:
  secretTargetRef:
  - parameter: bearerToken
    name: slurm-metrics-token-zkqtg
    key: token
