apiVersion: v1
kind: Service
metadata:
  name: slurm
  labels:
    app: slurm
spec:
  ports:
  - port: 6817
    name: slurmctld
  - port: 9092
    name: scrape
  selector:
    app: slurm
    component: head
