---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: compute
  labels:
    app: slurm
    component: compute
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: slurm
      component: compute
  serviceName: "compute"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: slurm
        component: compute
    spec:
      automountServiceAccountToken: false
      shareProcessNamespace: true
      dnsConfig:
        searches:
        - slurm.slurm-system.svc.cluster.local
      enableServiceLinks: false
      terminationGracePeriodSeconds: 10
      serviceAccountName: slurm
      initContainers:
      - name: fix-munge-paths
        image: quay.io/jkincl/munge:latest
        command:
        - sh
        - -c
        - /scripts/fix-munge-paths.sh
        volumeMounts:
        - name: munge-key
          mountPath: /etc/munge
        - name: munge-key-secret
          mountPath: /var/secrets/munge.key
          subPath: munge.key
        - name: munge-socket
          mountPath: /run/munge
      containers:
      - name: munge
        image: quay.io/jkincl/munge:latest
        command:
        - /sbin/munged
        - -F
        securityContext:
          runAsUser: 500
          runAsGroup: 500
          fsGroup: 500
        volumeMounts:
        - name: munge-socket
          mountPath: /run/munge
        - name: munge-key
          mountPath: /etc/munge
      - name: slurm
        image: quay.io/jkincl/slurm:latest
        command:
        - /sbin/slurmd
        - -D
        - -Z
        # - --conf
        # - RealMemory=4000
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: munge-socket
          mountPath: /run/munge
        - name: slurm-conf
          mountPath: /etc/slurm.conf
          subPath: slurm.conf
        # - name: shared
        #   mountPath: /home
      volumes:
      - name: munge-socket
        emptyDir: {}
      - name: munge-key
        emptyDir: {}
      - name: munge-key-secret
        secret:
          secretName: munge-key
      - name: slurm-conf
        configMap:
          name: slurm-conf
      # - name: shared
      #   nfs:
      #     server: 10.1.0.62
      #     path: /
