apiVersion: v1
kind: Service
metadata:
  name: compute
  labels:
    app: slurm
    component: compute
spec:
  ports:
  - port: 6818
    name: slurmd
  selector:
    app: slurm
    component: compute
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: compute
  labels:
    app: slurm
    component: compute
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: slurm
      component: compute
  serviceName: "compute"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: slurm
        component: compute
    spec:
      priorityClassName: high-priority-batch
      automountServiceAccountToken: false
      shareProcessNamespace: true
      dnsConfig:
        searches:
        - slurm.slurm-system.svc.cluster.local
      enableServiceLinks: false
      terminationGracePeriodSeconds: 15
      serviceAccountName: slurm
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - slurm
              - key: component
                operator: In
                values:
                - compute
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: fix-munge-paths
        image: image-registry.openshift-image-registry.svc:5000/slurm-system/munge:latest
        command:
        - sh
        - -c
        - /scripts/fix-munge-paths.sh
        volumeMounts:
        - name: munge-key
          mountPath: /etc/munge
        - name: munge-key-secret
          mountPath: /var/secrets/munge.key
          subPath: munge.key
        - name: munge-socket
          mountPath: /run/munge
      containers:
      - name: slurm
        image: image-registry.openshift-image-registry.svc:5000/slurm-system/slurm:latest
        command:
        - /sbin/slurmd
        - -D
        - -Z
        # - --conf
        # - RealMemory=4000
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                scontrol delete nodename=$HOSTNAME
        resources:
          requests:
            cpu: 3
          limits:
            cpu: 3
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: munge-socket
          mountPath: /run/munge
        - name: slurm-conf
          mountPath: /etc/slurm.conf
          subPath: slurm.conf
        - name: cgroup-conf
          mountPath: /etc/cgroup.conf
          subPath: cgroup.conf
        - name: shared
          mountPath: /home
      - name: munge
        image: image-registry.openshift-image-registry.svc:5000/slurm-system/munge:latest
        command:
        - /bin/bash
        - /scripts/munged-container.sh
        securityContext:
          runAsUser: 500
          runAsGroup: 500
          fsGroup: 500
        volumeMounts:
        - name: munge-socket
          mountPath: /run/munge
        - name: munge-key
          mountPath: /etc/munge
      volumes:
      - name: munge-socket
        emptyDir: {}
      - name: munge-key
        emptyDir: {}
      - name: munge-key-secret
        secret:
          secretName: munge-key
      - name: slurm-conf
        configMap:
          name: slurm-conf
      - name: cgroup-conf
        configMap:
          name: cgroup-conf

      - name: shared
        persistentVolumeClaim:
          claimName: shared-home
