apiVersion: v1
kind: Service
metadata:
  labels:
    app: authconfig
  name: authconfig
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: authconfig
  type: ClusterIP